# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5028:5028
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:\remote_debugger:rw
